USE [master]
GO
/** Object:  Database [BW_CA1_DW]    Script Date: 11/15/2017 12:29:57 PM **/
CREATE DATABASE [BW_CA1_DW]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BW_CA1_DW', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BW_CA1_DW.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'BW_CA1_DW_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\BW_CA1_DW_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [BW_CA1_DW] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BW_CA1_DW].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BW_CA1_DW] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET ARITHABORT OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BW_CA1_DW] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BW_CA1_DW] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BW_CA1_DW] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BW_CA1_DW] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [BW_CA1_DW] SET  MULTI_USER 
GO
ALTER DATABASE [BW_CA1_DW] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BW_CA1_DW] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BW_CA1_DW] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BW_CA1_DW] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [BW_CA1_DW] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [BW_CA1_DW] SET QUERY_STORE = OFF
GO
USE [BW_CA1_DW]
GO
ALTER DATABASE SCOPED CONFIGURATION SET IDENTITY_CACHE = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [BW_CA1_DW]
GO
/** Object:  Table [dbo].[Customers]    Script Date: 11/15/2017 12:29:57 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customers](
	[customerNumber] [int] NOT NULL,
	[city] [nvarchar](50) NULL,
	[state] [nvarchar](50) NULL,
	[country] [nvarchar](50) NULL,
	[creditLimit] [decimal](10, 2) NULL,
	[contactFirstName] [nvarchar](50) NULL,
	[contactLastName] [nvarchar](50) NULL,
	[phone] [nvarchar](50) NULL,
	[addressLine1] [nvarchar](50) NULL,
	[addressLine2] [nvarchar](50) NULL,
	[postalCode] [nvarchar](15) NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[customerNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/** Object:  Table [dbo].[Employees]    Script Date: 11/15/2017 12:29:57 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Employees](
	[employeeNumber] [int] NOT NULL,
	[extension] [nvarchar](50) NULL,
	[jobTitle] [nvarchar](50) NULL,
	[firstName] [nvarchar](50) NULL,
	[lastName] [nvarchar](50) NULL,
	[email] [nvarchar](100) NULL,
	[reportsTo] [int] NULL,
 CONSTRAINT [PK_Employees] PRIMARY KEY CLUSTERED 
(
	[employeeNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/** Object:  Table [dbo].[Offices]    Script Date: 11/15/2017 12:29:57 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Offices](
	[officeCode] [nvarchar](10) NOT NULL,
	[city] [nvarchar](50) NULL,
	[state] [nvarchar](50) NULL,
	[country] [nvarchar](50) NULL,
	[territory] [nvarchar](50) NULL,
 CONSTRAINT [PK_Offices] PRIMARY KEY CLUSTERED 
(
	[officeCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/** Object:  Table [dbo].[Products]    Script Date: 11/15/2017 12:29:57 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Products](
	[productCode] [nvarchar](15) NOT NULL,
	[productName] [nvarchar](70) NULL,
	[productScale] [nvarchar](10) NULL,
	[productVendor] [nvarchar](50) NULL,
	[buyPrice] [decimal](10, 2) NULL,
	[msrp] [decimal](10, 2) NULL,
	[productLine] [nvarchar](50) NULL,
 CONSTRAINT [PK_Products] PRIMARY KEY CLUSTERED 
(
	[productCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/** Object:  Table [dbo].[SalesFacts]    Script Date: 11/15/2017 12:29:57 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SalesFacts](
	[customerNumber] [int] NOT NULL,
	[productCode] [nvarchar](15) NOT NULL,
	[employeeNumber] [int] NOT NULL,
	[orderTimeKey] [int] NOT NULL,
	[requiredTimeKey] [int] NOT NULL,
	[shippedTimeKey] [int] NOT NULL,
	[officeCode] [nvarchar](10) NOT NULL,
	[orderNumber] [int] NOT NULL,
	[quantityOrdered] [int] NOT NULL,
	[priceEach] [decimal](10, 2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[customerNumber] ASC,
	[productCode] ASC,
	[employeeNumber] ASC,
	[orderTimeKey] ASC,
	[requiredTimeKey] ASC,
	[shippedTimeKey] ASC,
	[officeCode] ASC,
	[orderNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/** Object:  Table [dbo].[Time]    Script Date: 11/15/2017 12:29:57 PM **/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Time](
	[timeKey] [int] NOT NULL,
	[year] [int] NULL,
	[quarter] [int] NULL,
	[month] [int] NULL,
	[day] [int] NULL,
	[date] [datetime] NULL,
	[dayOfWeek] [nvarchar](10) NULL,
	[hour] [int] NULL,
	[minute] [int] NULL,
 CONSTRAINT [PK_Time] PRIMARY KEY CLUSTERED 
(
	[timeKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([customerNumber])
REFERENCES [dbo].[Customers] ([customerNumber])
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([employeeNumber])
REFERENCES [dbo].[Employees] ([employeeNumber])
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([officeCode])
REFERENCES [dbo].[Offices] ([officeCode])
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([orderTimeKey])
REFERENCES [dbo].[Time] ([timeKey])
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([productCode])
REFERENCES [dbo].[Products] ([productCode])
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([requiredTimeKey])
REFERENCES [dbo].[Time] ([timeKey])
GO
ALTER TABLE [dbo].[SalesFacts]  WITH CHECK ADD FOREIGN KEY([shippedTimeKey])
REFERENCES [dbo].[Time] ([timeKey])
GO
USE [master]
GO
ALTER DATABASE [BW_CA1_DW] SET  READ_WRITE 
GO
